config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'home#index'

  get 'demo_version', to: 'home#demo_version', as: 'demo_version'
  
  get 'statistics', to: 'statistics#statistics', as: 'statistics'
  get 'full_statistics_image', to: 'statistics#full_statistics_image', as: 'full_statistics_image'
  get 'statistics_per_month_image', to: 'statistics#statistics_per_month_image', as: 'statistics_per_month_image'
  get 'expense_type_statistics_image', to: 'statistics#expense_type_statistics_image', as: 'expense_type_statistics_image'
  get 'sum_statistics', to: 'statistics#sum_statistics', as: 'sum_statistics'

  get 'calendar', to: 'calendar#show_calendar', as: 'calendar'

  resources :categories, only: [:create, :index, :destroy, :update] do 
    post 'set_available'
    post 'set_unavailable'
  end

  resources :operations, only: [:create, :index, :destroy, :update] do
  end

  resources :budgets, only: [:index] do 
    collection do 
      post 'budgets_create'
      post 'budgets_update'
      patch 'budgets_copy'
      delete 'budgets_destroy'
    end
  end

end

app/models/budget.rb
class Budget < ActiveRecord::Base
  belongs_to :user
  belongs_to :category

  validates :category_id, uniqueness: { scope: :date }
end

app/controllers/budgets_controller.rb
class BudgetsController < ApplicationController
  before_action :authenticate_user!

  def index
    @budgets_hash = current_user.budgets.group_by{|b| b.date}.sort_by{|k, v| k}.reverse.to_h
    @categories = current_user.categories.order(:category_name).where(category_type: "Expense")
  end

  def budgets_create
    begin
      params_date = params['date'].split('-').map{|a| a.to_i}
      date = Date.new(*params_date)

      params['budgets'].each do |bp|
        b = Budget.new(budget_params(bp))
        b.user = current_user
        b.date = date
        b.save!
      end
    rescue => e
      flash[:danger] = I18n.t('budgets.duplicates_error')
    end
    redirect_to budgets_path
  end

  def budgets_destroy
    current_user.budgets.select{|b| b.date == Date.parse(params["format"])}.map{|b| b.destroy}
    redirect_to budgets_path
  end

  def budgets_update
    params['budgets'].each do |id, bp|
      b = Budget.find(id)
      b.update(budget_params(bp))
    end

    redirect_to budgets_path
  end

  def budgets_copy
    begin
      current_user.budgets.select{|b| b.date == Date.parse(params["format"])}.each do |budget|
        b = Budget.new
        b.amount = budget.amount
        b.category_id = budget.category_id
        b.date = Date.today.beginning_of_month
        b.user = current_user
        b.save!
      end
    rescue => e
      flash[:danger] = I18n.t('budgets.duplicates_error')
    end
    redirect_to budgets_path
  end

  def update
    @budget = Budget.find(params[:id])
    @budget.update(budget_params)

    redirect_to budgets_path
  end

  private
  def budget_params(bp)
    permit_params = bp.permit(:date, :amount, :category_id)
    permit_params['amount'] = permit_params['amount'].gsub(',', '.').to_f.round(2).to_s
    permit_params
  end

end

app/views/budgets/_add_budget.html.slim
= form_tag budgets_create_budgets_path, class: "form-horizontal" do
  .modal.fade#add_budget tabindex="-1" role="dialog"
    .modal-dialog role="document"
      .modal-content
        .modal-header 
          = I18n.t('budgets.add_budget')
        .modal-body
          .row
            = label_tag 'date', I18n.t('budgets.date'), class: 'control-label col-md-6'
            .col-md-6
              = text_field_tag :date, nil, autocomplete: "off", class: 'form-control datepicker-months', data: {provide: 'datepicker'}

          - @budgets = @categories.sort_by{|c| c.category_name}.map{|c| Budget.new(category: c)}
          - @budgets.each do |budget|
            = fields_for "budgets[]", budget do |bf|
              = bf.hidden_field :category_id
              .row 
                = bf.label :amount, budget.category.category_name, class: 'control-label col-md-6'
                .col-md-6
                  = bf.text_field :amount, autocomplete: "off", class: 'form-control'
              
        .modal-footer
          button.btn.custom-btn type="submit" 
            = I18n.t('save')
          button.btn.btn-default data-dismiss="modal" 
            = I18n.t('cancel')

app/views/budgets/_add_budget.slim
= form_tag budgets_create_budgets_path do
  .modal.fade#add_budget tabindex="-1" role="dialog"
    .modal-dialog role="document"
      .modal-content
        .modal-header 
          = I18n.t('budgets.add_budget')
        .modal-body
          .row
            .col-md-12
              .form-group
                = label_tag 'date', I18n.t('budgets.date')
                = text_field_tag :date, nil, class: 'form-control datepicker-months', data: {provide: 'datepicker'}, value: params[:date_to]

          - @budgets = @categories.map{|c| Budget.new(category: c)}
          - @budgets.each do |budget|
            = fields_for "budgets[]", budget do |bf|
              = bf.hidden_field :category_id
              .row 
                .col-md-12
                  = bf.label :amount, budget.category.category_name
                  = bf.text_field :amount, class: 'form-control'
              
        .modal-footer
          button.btn.custom-btn type="submit" 
            = I18n.t('save')
          button.btn.btn-default data-dismiss="modal" 
            = I18n.t('cancel')

app/views/budgets/_edit_form.html.slim
= form_tag budgets_update_budgets_path, class: "form-horizontal"  do
  .modal.fade id="budget_edit_#{budgets.first.date.to_s}" tabindex="-1" role="dialog"
    .modal-dialog role="document"
      .modal-content
        .modal-header 
          = I18n.t('budgets.edit_budget')
        .modal-body
          .row
            = label_tag 'date', I18n.t('budgets.date'), class: 'control-label col-md-6'
            .col-md-6
              = text_field_tag :date, nil, class: 'form-control datepicker-months', value: budgets.first.date.strftime("%Y-%m"), disabled: true

          - budgets.sort_by{|b| b.category.category_name}.each do |budget|
            = fields_for "budgets[]", budget do |bf|
              = bf.hidden_field :category_id
              = bf.hidden_field :id
              .row 
                = bf.label :amount, budget.category.category_name, class: 'control-label col-md-6'
                .col-md-6
                  = bf.text_field :amount, class: 'form-control'
              
        .modal-footer
          button.btn.custom-btn type="submit" 
            = I18n.t('save')
          button.btn.btn-default data-dismiss="modal" 
            = I18n.t('cancel')

app/views/budgets/_edit_forms.html.slim
- @budgets_hash.each do |date, budgets|
  = render partial: 'edit_form', locals: {budgets: budgets}

app/views/budgets/index.html.slim
.panel.panel-default
  .panel-heading
    = I18n.t('budgets.index')
    button.btn.btn-xs.custom-btn-lighter data-toggle="popover" data-placement="bottom" title=I18n.t('budgets.info')
      span.glyphicon.glyphicon-info-sign
    .btn-group.pull-right
      button.btn.btn-xs.custom-btn-lighter data-toggle="modal" data-target="#add_budget" type="button"
        span.glyphicon.glyphicon-plus
  .panel-body
    table.table.table-hover
      thead
        tr
          th width="20%" = I18n.t('budgets.date') 
          th width="70%" = I18n.t('budgets.category') 
          th width="10%"
      tbody 
      - @budgets_hash.each do |date, budgets|
          tr 
            td 
              = date.strftime("%Y-%m")
            td 
              .row 
                .col-md-4
                  b = I18n.t('budgets.sum')
                .col-md-8
                  b = budgets.map{|b| b.amount.to_f}.sum.round(2).to_s.gsub('.', I18n.t('decimal_separator'))
              - budgets.sort_by{|b| b.category.category_name}.each do |budget|
                - if budget.amount.to_i > 0
                  .row 
                    .col-md-4
                      = budget.category.category_name
                    .col-md-8
                      = budget.amount.to_s.gsub('.', I18n.t('decimal_separator'))
            td 
              .btn-group.pull-right
                button.btn.btn-xs.custom-btn data-toggle="modal" data-target="#budget_edit_#{date.to_s}"
                  span.glyphicon.glyphicon-pencil
                =link_to budgets_copy_budgets_path(date), class: 'btn btn-xs custom-btn', method: :patch
                  span.glyphicon.glyphicon-duplicate
                =link_to budgets_destroy_budgets_path(date), class: 'btn btn-xs custom-btn', method: :delete, data: {confirm: I18n.t('budgets.delete_confirmation_message')}
                  span.glyphicon.glyphicon-remove
= render "add_budget"
= render "edit_forms"