config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'home#index'

  get 'demo_version', to: 'home#demo_version', as: 'demo_version'
  
  get 'statistics', to: 'statistics#statistics', as: 'statistics'
  get 'full_statistics_image', to: 'statistics#full_statistics_image', as: 'full_statistics_image'
  get 'statistics_per_month_image', to: 'statistics#statistics_per_month_image', as: 'statistics_per_month_image'
  get 'expense_type_statistics_image', to: 'statistics#expense_type_statistics_image', as: 'expense_type_statistics_image'
  get 'sum_statistics', to: 'statistics#sum_statistics', as: 'sum_statistics'

  get 'calendar', to: 'calendar#show_calendar', as: 'calendar'

  resources :categories, only: [:create, :index, :destroy, :update] do 
    post 'set_available'
    post 'set_unavailable'
  end

  resources :operations, only: [:create, :index, :destroy, :update] do
  end

  resources :budgets, only: [:index] do 
    collection do 
      post 'budgets_create'
      post 'budgets_update'
      patch 'budgets_copy'
      delete 'budgets_destroy'
    end
  end

end

app/controllers/statistics_controller.rb
class StatisticsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_variables, except: [:sum_statistics]
  
  def statistics
    @general_statistics = @statistic_creator&.general_statistics
  end

  def full_statistics_image
    photo_data = @statistic_creator&.full_statistics
    if photo_data.nil?
      return photo_data
    end
    send_data(photo_data, :filename => 'full_statistics.png', :type => 'image/png', :disposition => "inline")
  end

  def statistics_per_month_image
    photo_data = @statistic_creator&.statistics_per_month
    if photo_data.nil?
      return photo_data
    end
    send_data(photo_data, :filename => 'statistics_per_month.png', :type => 'image/png', :disposition => "inline")
  end

  def expense_type_statistics_image
    photo_data = @statistic_creator&.expense_type_statistics
    if photo_data.nil?
      return photo_data
    end
    send_data(photo_data, :filename => 'expense_type_statistics.png', :type => 'image/png', :disposition => "inline")
  end

  def sum_statistics
    if params['date_to'].to_s.empty? 
      if params['date_from'].to_s.empty?
        return nil
      end
      params_date_from = params['date_from'].split('-').map{|a| a.to_i}
      original_date_from = Date.new(*params_date_from) 
      if original_date_from.month != Date.today.month
        return nil
      end

      @date_from = original_date_from.prev_month(3)
      @date_to = Date.new(*params_date_from).next_month.prev_day

      operations = current_user.operations.select{|o| o.date >= @date_from && o.date <= @date_to}
      
      @statistic_creator = Tools::StatisticCreator.new(nil, operations, nil)

      photo_data = @statistic_creator&.sum_statistics
      if photo_data.nil?
        return photo_data
      end
      return send_data(photo_data, :filename => 'sum_statistics.png', :type => 'image/png', :disposition => "inline")
    end
    nil
  end


  private
  def set_variables
    @statistic_creator = nil

    if params['date_from']
      params_date_from = params['date_from'].split('-').map{|a| a.to_i}
      params_date_to = params['date_to'].to_s.empty? ? params_date_from : params['date_to'].split('-').map{|a| a.to_i}

      @date_from ||= Date.new(*params_date_from)
      @date_to ||= Date.new(*params_date_to).next_month.prev_day

      if @date_from > @date_to
        flash[:danger] = I18n.t('statistics.date_validations')
      end

      operations ||= current_user.operations.select{|o| o.date >= @date_from && o.date <= @date_to}
      budgets ||= current_user.budgets.select{|b| b.date >= @date_from && b.date <= @date_to}

      @statistic_creator ||= Tools::StatisticCreator.new(current_user.categories, operations, budgets)
    end
  end
end

app/views/statistics/_statistics_form.html.slim
form action="statistics" method="get" enctype="multipart/form-data"
  .row.horizontal-form
    .col-md-5
      .form-group
        = label_tag 'date_from'
          = I18n.t('statistics.date_from')
        = text_field_tag :date_from, nil, autocomplete: "off", class: 'form-control datepicker-months', data: {provide: 'datepicker'}, value: params[:date_from]

    .col-md-5
      .form-group
        = label_tag 'date_to'
          = I18n.t('statistics.date_to')
        = text_field_tag :date_to, nil, autocomplete: "off", class: 'form-control datepicker-months', data: {provide: 'datepicker'}, value: params[:date_to]

    .col-md-2
      .form-group
        button.btn.custom-btn.btn-block type="submit"
          = I18n.t('submit')

app/views/statistics/_statistics_list.html.slim
li.list-group-item
  .row
    .col-md-1
      button.btn.btn-xs.btn-default.small.u-clickable data-toggle="collapse" data-target=".js-operation-#{operations_hash[:category_id]}"
        span.collapse.in class="js-operation-#{operations_hash[:category_id]}"
          span.glyphicon.glyphicon-collapse-down
        span.collapse class="js-operation-#{operations_hash[:category_id]}"
          span.glyphicon.glyphicon-collapse-up
    .col-md-6.title
      = operations_hash[:category]
    .col-md-5
      = operations_hash[:sum].to_s.gsub('.', I18n.t('decimal_separator'))
  table.table.table-hover.collapse class="js-operation-#{operations_hash[:category_id]}"
    tbody
      - operations_hash[:operations].each do |operation|
        tr
          td width = "20%"
            = operation.date  
          td width = "20%"
            = operation.amount.to_s.gsub('.', I18n.t('decimal_separator'))
          td width = "60%"
            - if operation.description.length > 71 
              = operation.description[0..70] + "(...)"
            - else
              = operation.description

app/views/statistics/statistics.html.slim
== render 'statistics_form'

- if @general_statistics
  .row
    .col-md-6
      .panel.panel-default
        .panel-heading
          = I18n.t('operations.expenses')
        .panel-body
          ul.list-group
            li.list-group-item
              .row
                .col-md-6.title
                  = I18n.t('statistics.expenses_sum')
                .col-md-6
                  = @general_statistics[:expenses_sum].to_s.gsub('.', I18n.t('decimal_separator'))
            - @general_statistics[:grouped_expenses_operations].each do |operations_hash|
              - if operations_hash[:sum] > 0
                == render partial: 'statistics_list', locals: {operations_hash: operations_hash}

    .col-md-6
      .panel.panel-default
        .panel-heading
          = I18n.t('operations.incomings')
        .panel-body
          ul.list-group.hover
            li.list-group-item
              .row
                .col-md-6.title
                  = I18n.t('statistics.incomings_sum')
                .col-md-6
                  = @general_statistics[:incomings_sum].to_s.gsub('.', I18n.t('decimal_separator'))
            - @general_statistics[:grouped_incomings_operations].each do |operations_hash|
              == render partial: 'statistics_list', locals: {operations_hash: operations_hash}
  .row
    .col-md-12
      .panel.panel-default
        .panel-heading
          = I18n.t('operations.expenses')
        .panel-body
          - if @general_statistics[:grouped_expenses_operations].empty?
            = I18n.t('statistics.no_statistics')
          - else
            - budget_sum = @general_statistics[:grouped_expenses_operations].map{|o| o[:budget_amount]}.sum.round(2)
            - if budget_sum > 0
              .row
                .col-md-12
                  = t('sum')
              .row
                .col-md-12
                  .progress
                    - sum = @general_statistics[:grouped_expenses_operations].map{|o| o[:sum]}.sum.round(2)
                    - percent = (sum/budget_sum * 100).round
                    - percent_value = percent
                    - if percent_value > 100
                      - percent_value = 100
                    - progress_bar_class = 'progress-bar-success'
                    - if percent > 50
                      - progress_bar_class = 'progress-bar-warning'
                    - if percent > 80
                      - progress_bar_class = 'progress-bar-danger'

                    .progress-bar.progress-bar-striped class=progress_bar_class role="progressbar" aria-valuenow="60" aria-valuemin="0" aria-valuemax="100" style="min-width: 2em; width: #{percent_value}%;"
                      = percent.to_s + "% (#{sum.to_s} z #{budget_sum})" 

            - @general_statistics[:grouped_expenses_operations].sort_by{|h| h[:category]}.each do |operations_hash|
              - if operations_hash[:budget_amount] > 0
                .row
                  .col-md-12
                    = operations_hash[:category]
                .row
                  .col-md-12
                    .progress
                      - percent = (operations_hash[:sum]/operations_hash[:budget_amount] * 100).round
                      - percent_value = percent
                      - if percent_value > 100
                        - percent_value = 100
                      - progress_bar_class = 'progress-bar-success'
                      - if percent > 50
                        - progress_bar_class = 'progress-bar-warning'
                      - if percent > 80
                        - progress_bar_class = 'progress-bar-danger'

                      .progress-bar.progress-bar-striped class=progress_bar_class role="progressbar" aria-valuenow="60" aria-valuemin="0" aria-valuemax="100" style="min-width: 2em; width: #{percent_value}%;"
                        = percent.to_s + "% (#{operations_hash[:sum].to_s} z #{operations_hash[:budget_amount]})" 


  - if @general_statistics[:expenses_sum] > 0
    - full_statistics_image_src = full_statistics_image_path(date_from: params[:date_from], date_to: params[:date_to])
    - statistics_per_month_image_src = statistics_per_month_image_path(date_from: params[:date_from], date_to: params[:date_to])
    - expense_type_statistics_image_src = expense_type_statistics_image_path(date_from: params[:date_from], date_to: params[:date_to])

    .row 
      .col-md-6
        img style="max-width:100%" src=full_statistics_image_src
      .col-md-6
        img style="max-width:100%" src=statistics_per_month_image_src
    .row 
      .col-md-6
        img style="max-width:100%" src=expense_type_statistics_image_src
      .col-md-6
        - if params[:date_from].split('-').last.to_i == Date.today.month && params[:date_to].nil?
          - sum_statistics_src = sum_statistics_path(date_from: params[:date_from], date_to: params[:date_to])
          img style="max-width:100%" src=sum_statistics_src