config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'home#index'

  get 'demo_version', to: 'home#demo_version', as: 'demo_version'
  
  get 'statistics', to: 'statistics#statistics', as: 'statistics'
  get 'full_statistics_image', to: 'statistics#full_statistics_image', as: 'full_statistics_image'
  get 'statistics_per_month_image', to: 'statistics#statistics_per_month_image', as: 'statistics_per_month_image'
  get 'expense_type_statistics_image', to: 'statistics#expense_type_statistics_image', as: 'expense_type_statistics_image'
  get 'sum_statistics', to: 'statistics#sum_statistics', as: 'sum_statistics'

  get 'calendar', to: 'calendar#show_calendar', as: 'calendar'

  resources :categories, only: [:create, :index, :destroy, :update] do 
    post 'set_available'
    post 'set_unavailable'
  end

  resources :operations, only: [:create, :index, :destroy, :update] do
  end

  resources :budgets, only: [:index] do 
    collection do 
      post 'budgets_create'
      post 'budgets_update'
      patch 'budgets_copy'
      delete 'budgets_destroy'
    end
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @welcome_message = if user_signed_in?
      I18n.t('welcome.welcome_messages.signed_in')
    else
      I18n.t('welcome.welcome_messages.signed_out')
    end

    cookies[:glupie_ciasteczko] = {
      :value => "Jakieś głupie ciasteczko",
      :expires => Time.now + 6.months,
      # :domain => ['.localhost.com'] #zapisuje na subdomain
      # :domain => %w(.localhost) #nigdzie nie zapisuje
      # :domain => '.localhost.com' #nigdzie nie zapisuje
      :domain => 'herokuapp.com' #nigdzie nie zapisuje
      # :domain => :all #zapisuje na subdomain
    }

    cookies[:glupie_ciasteczko2] = {
      :value => "Jakieś głupie ciasteczko",
      :expires => Time.now + 6.months,
      :domain => ['.herokuapp.com'] #zapisuje na subdomain
      # :domain => %w(.localhost) #nigdzie nie zapisuje
      # :domain => '.localhost.com' #nigdzie nie zapisuje
      # :domain => 'herokuapp.com' #nigdzie nie zapisuje
      # :domain => :all #zapisuje na subdomain
    }

    cookies[:glupie_ciasteczko3] = {
      :value => "Jakieś głupie ciasteczko",
      :expires => Time.now + 6.months,
      # :domain => ['.herokuapp.com'] #zapisuje na subdomain
      # :domain => %w(.localhost) #nigdzie nie zapisuje
      # :domain => '.localhost.com' #nigdzie nie zapisuje
      # :domain => 'herokuapp.com' #nigdzie nie zapisuje
      # :domain => :all #zapisuje na subdomain
    }

    cookies[:glupie_ciasteczko3] = {
      :value => "Jakieś głupie ciasteczko",
      :expires => Time.now + 6.months,
      # :domain => ['.herokuapp.com'] #zapisuje na subdomain
      :domain => %w(.herokuapp) #nigdzie nie zapisuje
      # :domain => '.localhost.com' #nigdzie nie zapisuje
      # :domain => 'herokuapp.com' #nigdzie nie zapisuje
      # :domain => :all #zapisuje na subdomain
    }
  end

  def demo_version
    sign_in(User.where(email: 'demo@example.com').first, scope: :user)
    redirect_to root_path
  end
end

app/views/home/_header.html.slim
nav.navbar.navbar-default.navbar-static-top role="navigation" 
  .container-fluid
    a.navbar-brand 
      span.glyphicon.glyphicon-home
      = I18n.t('application_name')
    .collapse.navbar-collapse
      ul.nav.navbar-nav
        - if user_signed_in?
          li= active_link_to I18n.t('categories.index'), categories_path
          li= active_link_to I18n.t('operations.index'), operations_path
          li= active_link_to I18n.t('budgets.index'), budgets_path
          li= active_link_to I18n.t('calendar.index'), calendar_path
          li= active_link_to I18n.t('statistics.index'), statistics_path(date_from: Date.today.strftime("%Y-%m"))
          - unless current_user.email == 'demo@example.com'
            li= active_link_to I18n.t('user.edit'), edit_user_registration_path
          li= active_link_to I18n.t('user.logout'), destroy_user_session_path, method: :delete
        - else
          li= active_link_to I18n.t('user.registration'), new_user_registration_path
          li= active_link_to I18n.t('user.login'), user_session_path
          li= active_link_to I18n.t('demo'), demo_version_path
      ul.nav.navbar-nav.pull-right
        li.dropdown
          a.dropdown-toggle data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"
            span.glyphicon.glyphicon-globe
            span.caret
          ul.dropdown-menu.dropdown-menu-right
            li 
              = link_to params.permit(:locale, :user_id, :category_id, :date_from, :date_to).merge({:locale => :pl}), :wrap_tag => :li
                span = image_tag("pl.jpg", :alt => "pl", style: "border: 1px solid black" )
                span = " Polski"
            li 
              = link_to params.permit(:locale, :user_id, :category_id, :date_from, :date_to).merge({:locale => :en}), :wrap_tag => :li
                span = image_tag("en.jpg", :alt => "en", style: "border: 1px solid black")
                span = " English"
        

app/views/home/index.html.slim
.jumbotron
  h1 = @welcome_message