config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'home#index'

  get 'demo_version', to: 'home#demo_version', as: 'demo_version'
  
  get 'statistics', to: 'statistics#statistics', as: 'statistics'
  get 'full_statistics_image', to: 'statistics#full_statistics_image', as: 'full_statistics_image'
  get 'statistics_per_month_image', to: 'statistics#statistics_per_month_image', as: 'statistics_per_month_image'
  get 'expense_type_statistics_image', to: 'statistics#expense_type_statistics_image', as: 'expense_type_statistics_image'
  get 'sum_statistics', to: 'statistics#sum_statistics', as: 'sum_statistics'

  get 'calendar', to: 'calendar#show_calendar', as: 'calendar'

  resources :categories, only: [:create, :index, :destroy, :update] do 
    post 'set_available'
    post 'set_unavailable'
  end

  resources :operations, only: [:create, :index, :destroy, :update] do
  end

  resources :budgets, only: [:index] do 
    collection do 
      post 'budgets_create'
      post 'budgets_update'
      patch 'budgets_copy'
      delete 'budgets_destroy'
    end
  end

end

app/models/category.rb
class Category < ActiveRecord::Base
  belongs_to :user

  has_many :operations, dependent: :destroy
  has_many :budgets, dependent: :destroy
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, except: [:index, :create, :destroy]

  def index
    if user_signed_in?
      @categories = current_user.categories.order(:category_type, :category_name)
    end
  end

  def create
    c = Category.new(category_params)
    c.user = current_user
    c.save!

    redirect_to categories_path
  end

  def destroy
    Category.destroy(params[:id])
    redirect_to categories_path
  end

  def update
    @category.update(category_edit_params)

    redirect_to categories_path
  end

  def set_available
    @category.available = true
    @category.save!

    redirect_to categories_path
  end

  def set_unavailable
    @category.available = false
    @category.save!

    redirect_to categories_path
  end

  private
  def category_params
    params.require(:category).permit(:category_name, :category_type)
  end

  def category_edit_params
    params.require(:category).permit(:category_name)
  end

  def set_category
    @category = Category.find(params[:id] || params[:category_id])
  end

end

app/views/categories/_add_category.html.slim
= form_for :category, url: categories_path, turboboost: true, method: :post  do |f|
  .modal.fade#add_category tabindex="-1" role="dialog"
    .modal-dialog role="document"
      .modal-content
        .modal-header 
          = I18n.t('categories.add_category')
        .modal-body
          .row
            .col-md-6
              .form-group
                = f.label :category_name, I18n.t('categories.category_name')
                = f.text_field :category_name, class: 'form-control'
            .col-md-6
              .form-group
                = f.label :category_type, I18n.t('categories.category_type')
                = f.select :category_type, ['Expense', 'Incoming'].map{|o| [I18n.t("operations.#{o.downcase}"), o]}, {}, {class: 'form-control'}
        .modal-footer
          button.btn.custom-btn type="submit" 
            = I18n.t('save')
          button.btn.btn-default data-dismiss="modal" 
            = I18n.t('cancel')

app/views/categories/_edit_form.html.slim
= form_for category, url: category_path(category),  turboboost: true, method: :patch  do |f|
  .modal.fade id="category_edit_#{category.id}" tabindex="-1" role="dialog"
    .modal-dialog role="document"
      .modal-content
        .modal-header 
          = I18n.t('categories.edit_category')
        .modal-body
          .row
            .col-md-12
              .form-group
                = f.label :category_name, I18n.t('categories.category_name')
                = f.text_field :category_name, class: 'form-control'
        .modal-footer
          button.btn.custom-btn type="submit" 
            = I18n.t('save')
          button.btn.btn-default data-dismiss="modal" 
            = I18n.t('cancel')

app/views/categories/_edit_forms.html.slim
- @categories.each do |category|
  = render partial: 'edit_form', locals: {category: category}

app/views/categories/index.html.slim
.panel.panel-default
  .panel-heading
    = I18n.t('categories.index')
    .btn-group.pull-right
      button.btn.btn-xs.custom-btn-lighter data-toggle="modal" data-target="#add_category" type="button"
        span.glyphicon.glyphicon-plus
  .panel-body
    table.table.table-hover
      thead
        tr
          th width="25%" = I18n.t('categories.category_name') 
          th width="65%" = I18n.t('categories.category_type') 
          th width="10%"
      tbody 
      - @categories.each do |category|
        - klass = ""
        - if !category.available then klass = "unavailable"
        tr class="#{klass}" 
          td 
            = category.category_name
          td 
            = I18n.t("operations.#{category.category_type.downcase}") 
          td 
            .btn-group.pull-right
              - if category.available
                =link_to category_set_unavailable_path(category), class: 'btn btn-xs custom-btn', method: :post
                  span.glyphicon.glyphicon-star
              - else
                =link_to category_set_available_path(category), class: 'btn btn-xs custom-btn', method: :post
                  span.glyphicon.glyphicon-star-empty
              button.btn.btn-xs.custom-btn data-toggle="modal" data-target="#category_edit_#{category.id}"
                span.glyphicon.glyphicon-pencil
              =link_to category_path(category), class: 'btn btn-xs custom-btn', method: :delete, data: {confirm: I18n.t('categories.delete_confirmation_message')}, disabled: (@categories.where(category_type: category.category_type).length == 1 )
                span.glyphicon.glyphicon-remove


= render "add_category"
= render "edit_forms"